"""auto update

Revision ID: 18d4e8f02c32
Revises: 304abe440d62
Create Date: 2026-03-08 11:53:53.831881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18d4e8f02c32'
down_revision: Union[str, Sequence[str], None] = '304abe440d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('checked_by', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('checked_at', sa.String(), nullable=True))
    op.drop_column('tasks', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'checked_at')
    op.drop_column('tasks', 'checked_by')
    # ### end Alembic commands ###