"""auto update

Revision ID: 304abe440d62
Revises: 4d75fcdad71f
Create Date: 2026-03-07 09:58:29.789117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304abe440d62'
down_revision: Union[str, Sequence[str], None] = '4d75fcdad71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('worker_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_visits_id'), 'room_visits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_visits_id'), table_name='room_visits')
    op.drop_table('room_visits')
    # ### end Alembic commands ###